### ISSUE TITLE
problem setting up shared folder for the yosemite VM .

### ISSUE THREAD

**Issue by rjdp** [AndrewDryga/vagrant-box-osx#24]
![image](https://cloud.githubusercontent.com/assets/7734938/8324179/4a67492a-1a6b-11e5-8edd-dd7c2f6671f2.png)

**Comment by SpaceK33z** [comment]
Have you tried it using NFS? This works for me at least. Put this in your Vagrantfile:

```
# Use NFS for the shared folder
  config.vm.synced_folder ".", "/vagrant",
    id: "core",
    :nfs => true,
    :mount_options => ['nolock,vers=3,udp,noatime']
```

**Comment by rjdp** [comment]
![screenshot from 2015-06-26 17 09 50](https://cloud.githubusercontent.com/assets/7734938/8376559/3b6bb232-1c26-11e5-81f2-bc877353bee8.png)

**Comment by SpaceK33z** [comment]
No idea if this helps anything, but can you change that line to `config.vm.network :private_network, ip: "10.10.10.10"`?

**Comment by rjdp** [comment]
dindnt help .. thanks anyways ....gave same error as in last pic .

**Comment by AndrewDryga** [comment]
This happens because VirtualBox doesn't have guest additions for Mac. But you can try to use Samba/NFS shared folders. (SpaceK33z example works for me.)

**Comment by AndrewDryga** [comment]
I've released new version of box and added sample config for NFS folders. Can you try it and confirm if issue is fixed?

**Comment by WayneBuckhanan** [comment]
@rjdp, have you checked the networking settings in Virtualbox itself? Worth confirming that the network is host-only when defining the private network.

**Comment by mh-cbon** [comment]
hi,

In my setup NFS sharing did not work.

My system,
```
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree
[mh-cbon@pc12 has-launchd] $ vagrant -v
Vagrant 1.8.1
```

Solution found,
Use rsync on a writable folder (one into /Users/vagrant/)
```
      config.vm.synced_folder ".", "/Users/vagrant/wd2", type: "rsync"
```

**Comment by rootion** [comment]
I am having issues getting the shared folders to work in sierra.
I am reopening this issue because I am dealing with the same code snippets provided above, but I can open a new issue if it shouldn't be here.

The NFS snippet in the sample vagrantfile provided with the box gave me the following error:
```
NFS requires a host-only network to be created.
Please add a host-only network to the machine (with either DHCP or a
static IP) for NFS to work.
```
Couldn't get it to work, so I tried the rsync approach which was shared in the last message in this thread:
`config.vm.synced_folder ".", "/Users/vagrant/wd2", type: "rsync"`

While provisioning this box, it gives me the following message
`==> default: Rsyncing folder: /home/username/osx_sierra/ => /Users/vagrant/wd2`
and it seems to load fine, however there is no live syncing happening at all. I need to do `vagrant reload` in order to get my files updated everytime.

Why is not live syncing happening at all? My host machine is running Ubuntu 16.04.

This is my vagrant file: 
```
Vagrant.configure(2) do |config|
  config.vm.box = "http://files.dryga.com/boxes/osx-sierra-0.3.1.box"
  config.vm.synced_folder ".", "/Users/vagrant/wd2", type: "rsync"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["setextradata", :id, "VBoxInternal2/EfiGopMode", "4"]
  end
end
```
