### ISSUE TITLE
Running apps with GUI

### ISSUE THREAD

**Issue by crdoconnor** [AndrewDryga/vagrant-box-osx#31]
Is there any way to run apps using a GUI on the mavericks box?

I've tried enabling regular VNC (I see an unusable grey screen), Vine (doesn't work), X11vnc (likewise). The box doesn't boot into a desktop environment, either for some reason (although it does on the yosemite box and it works fine).

Ideally, I'd prefer to use ssh with X forwarding, but that doesn't appear to be an option.

**Comment by Meistache** [comment]
+1 here, specially because I need to test this box with a jenkins local instance without external network access for test purposes (and I'm on a really low bandwidth network connection so it would spend 3 more days of ETA). I'd be very thankful for that.

**Comment by WayneBuckhanan** [comment]
Have you tried all the recommendations in the closed ["GUI mode?" issue](https://github.com/AndrewDryga/vagrant-box-osx/issues/26) yet? 
I suspect the different CPU ID between the earlier Mavericks box and the updated Yosemite box may be your issue. I can redownload the Mavericks box to test later if you're still having trouble.

**Comment by Meistache** [comment]
I'll try it and feedback it later, thank you!

**Comment by Meistache** [comment]
So, I had a long time dealing with this in order to assure I was not doing anything wrong. But after all, all I got is a blank screen and vagrant trying to connect into SSH without success, which makes me suspect it doesn't load a kernel at all. I tried using minimal configuration on Vagrantfile (only the hardware fixes and screen resolution besides defining the box and gui=true but it was useless.

**Comment by WayneBuckhanan** [comment]
@Meistache What is showing up in the Virtualbox GUI? You should be getting messages in the console even if it doesn't ever boot the OSX desktop.

**Comment by crdoconnor** [comment]
That's what I get. The messages appear but the desktop doesn't.

**Comment by WayneBuckhanan** [comment]
@crdoconnor What is the last message that appears?
I was stuck for the longest time just after a bluetooth message, then changed the CPU ID and was able to boot the rest of the way into the desktop. I believe @AndrewDryga updated the CPU ID in the Yosemite box, but you'll have to do it in the [Vagrantfile](https://gist.github.com/WayneBuckhanan/15de1bb8b3fb3bd4f7af) manually.

FYI, the setextradata lines in the linked gist may be needed if you are not running it on non-Apple hardware.

**Comment by Meistache** [comment]
@crdoconnor Wayne's recommendation should work for sure.
@WayneBuckhanan it just doesn't show anything, no messages, just blank screen. I suspect I need to pass some other hardware adjust on Vagrantfile to go through, some hardware model thing. I'm on a ASUS Vivobook S550CA. 

I say that because I got the same blank screen trying a Unibeast boot for my tests, just saying.

**Comment by WayneBuckhanan** [comment]
Good ~~luck~~ skill, @Meistache. I have been known to play with settings in the Virtualbox interface once the vagrant box has been brought up. When you get it to work, I'd be interested to hear what made the difference!

**Comment by Meistache** [comment]
Oh, I just passed by to thank you for the assistance, @WayneBuckhanan. I actually quit trying to find a solution (and I tried a lot), had a busy week and then I just downloaded Yosemite (it was a pain) and it's running nice and nifty.
